default: &default
  adapter: mysql2
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  encoding: utf8mb4
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  database: <%= ENV.fetch("DB_NAME") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: bloomtest_test
